app:
  tty: true
  stdin_open: true
  build: .
  command: bash -c "foreman start -f Procfile -p 3000"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
postgres:
  image: postgres:9.6
  ports:
    - "5432"
redis:
  image: redis:3.2
  ports:
    - '6379:6379'
