default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: astronomania-api_development
test:
  <<: *default
  database: astronomania-api_test
production:
  <<: *default
  database: astronomania-api_production
  username: astronomania-api
  password: <%= ENV['ASTRONOMANIA-API_DATABASE_PASSWORD'] %>
